version: 0.2

phases:
	pre-build:
		commands:
		- echo entering pre-build phase...
	build:
		commands:
		-echo starting build...
		- mvn clean prepare-package war:exploded
	post-build:
		commands:
		- echo moving exploded war to root
		- mvn -v target/deploy .
artifacts:
	files:
	- deploy/**/*