version: 0.2
phases:
  pre_build:
    commands:
      - echo entering pre-build phase...
      - cd simple-rest/
  build:
    commands:
      - echo starting build...
      - mvn clean prepare-package war:exploded
  post_build:
    commands:
      - echo moving exploded war to root
      - mvn -v target/deploy .
artifacts:
  files:
    - deploy/**/*